In [5]:
# Mannual ccx , swap,   hardcorde script


import numpy as np

## 1. MANUALLY HARDCODED 4x4 SWAP MATRIX (2 Qubits)
## Maps: |00> -> |00>, |01> -> |10>, |10> -> |01>, |11> -> |11>

manual_swap = np.array([
    [1, 0, 0, 0],  # Row for |00>
    [0, 0, 1, 0],  # Row for |01> -> Swaps with |10>
    [0, 1, 0, 0],  # Row for |10> -> Swaps with |01>
    [0, 0, 0, 1]   # Row for |11>
])

print("--- Manual SWAP Matrix (4x4) ---")
print(manual_swap)

## 2. MANUALLY HARDCODED 8x8 CCX (TOFFOLI) MATRIX (3 Qubits)
## Only flips the last two states: |110> <-> |111Object

manual_ccx = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],  # |000> stays same
    [0, 1, 0, 0, 0, 0, 0, 0],  # |001> stays same
    [0, 0, 1, 0, 0, 0, 0, 0],  # |010> stays same
    [0, 0, 0, 1, 0, 0, 0, 0],  # |011> stays same
    [0, 0, 0, 0, 1, 0, 0, 0],  # |100> stays same
    [0, 0, 0, 0, 0, 1, 0, 0],  # |101> stays same
    [0, 0, 0, 0, 0, 0, 0, 1],  # |110> flips to |111>
    [0, 0, 0, 0, 0, 0, 1, 0]   # |111> flips to |110>
])

print("\n--- Manual CCX Matrix (8x8) ---")
print(manual_ccx)

## EXAMPLE 1: SWAP

initial_state_2q = np.array([0, 1, 0, 0])
final_state_2q = manual_swap @ initial_state_2q
print("SWAP\n")
print("Initial statevector:", initial_state_2q)
print("Final statevector :", final_state_2q)
print("Result: swapped successfully!\n")

## EXAMPLE 2: CCX (Toffoli)
initial_state_3q = np.array([0, 0, 0, 0, 0, 0, 1, 0])
final_state_3q = manual_ccx @ initial_state_3q
print("CCX\n")
print("Initial statevector:", initial_state_3q)
print("Final statevector:  ", final_state_3q)


--- Manual SWAP Matrix (4x4) ---
[[1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]]

--- Manual CCX Matrix (8x8) ---
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]
SWAP

Initial statevector: [0 1 0 0]
Final statevector : [0 0 1 0]
Result: swapped successfully!

CCX

Initial statevector: [0 0 0 0 0 0 1 0]
Final statevector:   [0 0 0 0 0 0 0 1]


In [17]:
# generate unitary matrix by script
import qiskit as qk
from qiskit.quantum_info import Operator

def generate_matrix(num_qubits, gate_type):
    qc = qk.QuantumCircuit(num_qubits)
        
    gate_type = gate_type.lower()
    if gate_type == "ccx" and num_qubits >= 3:
        # CCX uses control 0, control 1, and target 2
        qc.ccx(0, 1, 2)
    elif gate_type == "swap" and num_qubits >= 2:
        # SWAP exchanges qubit 0 and qubit 1
        qc.swap(0, 1)
    else:
        print(f"--> Note: {num_qubits} qubits is too small for a '{gate_type.upper()}' gate layout.")
        
    unitary_operator = Operator(qc)
    return unitary_operator.data.real.astype(int)


user_qubits = int(input("Enter number of qubits (e.g., 2, 3, 4): "))
user_gate = input("Enter gate type ('ccx' or 'swap'): ")

# Call the function using user input variables
final_matrix = generate_matrix(user_qubits, user_gate)

print(f"\nResulting {user_gate.upper()} Matrix for {user_qubits} Qubits:")
print(final_matrix)

Enter number of qubits (e.g., 2, 3, 4):  3
Enter gate type ('ccx' or 'swap'):  ccx



Resulting CCX Matrix for 3 Qubits:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
