In [4]:
import numpy as np


def build_oracle_matrix(n, f):
    """Build the 2^(2n) x 2^(2n) unitary matrix for the oracle U_f."""
    dim = 4**n  # 2^(2n) total basis states
    U = np.zeros((dim, dim), dtype=complex)

    for x_int in range(2**n):
        x = tuple((x_int >> (n - 1 - i)) & 1 for i in range(n))
        fx = f[x]

        for y_int in range(2**n):
            y = tuple((y_int >> (n - 1 - i)) & 1 for i in range(n))

            y_xor_fx = tuple(y[i] ^ fx[i] for i in range(n))
            y_xor_fx_int = sum(b << (n - 1 - i) for i, b in enumerate(y_xor_fx))

            input_idx = x_int * (2**n) + y_int
            output_idx = x_int * (2**n) + y_xor_fx_int

            U[output_idx, input_idx] = 1.0
    return U


# 1. Set your n here
n = 3

# 2. Define your mapping directly here (Tuples of 0s and 1s)
# This matches the mapping from your screenshot!
f_custom = {
    (0, 0, 0): (1, 0, 0),
    (0, 0, 1): (0, 0, 1),
    (0, 1, 0): (1, 0, 1),
    (0, 1, 1): (1, 1, 1),
    (1, 0, 0): (0, 0, 1),
    (1, 0, 1): (1, 0, 0),
    (1, 1, 0): (1, 1, 1),
    (1, 1, 1): (1, 0, 1),
}

# 3. Generate the matrix
oracle_matrix = build_oracle_matrix(n, f_custom)

# 4. Display the entire matrix without truncation
matrix_dim = 4**n
print(
    f"--- Custom Oracle Matrix ({matrix_dim}×{matrix_dim} Permutation Matrix) ---"
)
np.set_printoptions(threshold=np.inf, linewidth=300)
print(oracle_matrix.real.astype(int))

# 5. Verify Unitarity
product = oracle_matrix @ oracle_matrix.conj().T
is_unitary = np.allclose(product, np.eye(matrix_dim))
print(f"\nIs the generated oracle matrix unitary? {is_unitary}")

--- Custom Oracle Matrix (64×64 Permutation Matrix) ---
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0